language: php

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

env:
  matrix:
    - LARAVEL=^5.8 TESTBENCH=^3.8 PHPUNIT=^7.5
    - LARAVEL=^6.0 TESTBENCH=^4.0 PHPUNIT=^8.0

matrix:
  fast_finish: true
  exclude:
    - php: 7.1
      env: LARAVEL=^6.0 TESTBENCH=^4.0 PHPUNIT=^8.0

cache:
  directories:
    - $HOME/.composer/cache

branches:
  only:
    - master

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - travis_retry composer require "illuminate/validation:${LARAVEL}" "illuminate/container:${LARAVEL}" "illuminate/support:${LARAVEL}" "illuminate/translation:${LARAVEL}" "phpunit/phpunit:${PHPUNIT}" "orchestra/testbench:${TESTBENCH}" --prefer-dist --no-interaction --no-suggest

script: vendor/bin/phpunit